version: "3"
services:
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  outline:
    image: outline:v001
    entrypoint: "sh entrypoint.sh"
    build:
      context: ./outline-build
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/opt/outline/.env
    depends_on:
      - postgres
      - redis
